# Generated by Django 4.1.6 on 2023-05-05 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Stocks",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company", models.CharField(default="", max_length=128)),
                ("ticker", models.CharField(max_length=128)),
                ("one_pred", models.FloatField(blank=True, default=None, null=True)),
                ("three_pred", models.FloatField(blank=True, default=None, null=True)),
            ],
        ),
    ]
