# Generated by Django 4.1.6 on 2023-05-06 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stock", "0002_stocks_update_time"),
    ]

    operations = [
        migrations.CreateModel(
            name="Overview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company", models.CharField(default="", max_length=128)),
                ("ticker", models.CharField(max_length=128)),
                ("date", models.DateField(blank=True, default=None, null=True)),
                ("open", models.FloatField(blank=True, default=None, null=True)),
                ("high", models.FloatField(blank=True, default=None, null=True)),
                ("low", models.FloatField(blank=True, default=None, null=True)),
                ("close", models.FloatField(blank=True, default=None, null=True)),
                ("adjclose", models.FloatField(blank=True, default=None, null=True)),
                ("volume", models.IntegerField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.AddField(
            model_name="stocks",
            name="current",
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="stocks",
            name="one_pred_diff",
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="stocks",
            name="seven_pred",
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="stocks",
            name="seven_pred_diff",
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="stocks",
            name="three_pred_diff",
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
